### ISSUE TITLE
`method_missing': undefined local variable or method `git_url' 

### ISSUE THREAD

**Issue by masterkain** [jrochkind/cap_git_tools#4]
```
/Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/capistrano-2.14.2/lib/capistrano/configuration/namespaces.rb:193:in `method_missing': undefined local variable or method `git_url' for #<Capistrano::Configuration::Namespaces::Namespace:0x007fe403b6ea38> (NameError)
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:207:in `block in upstream_remote_by_url'
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:207:in `each'
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:207:in `find'
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:207:in `upstream_remote_by_url'
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:55:in `upstream_remote'
  from /Users/kain/.rvm/gems/ruby-2.0.0-p0@myapp/gems/cap_git_tools-0.9.0/lib/cap_git_tools/task_helpers.rb:22:in `ensure_git_fetch'
```

**Comment by dnd** [comment]
This should now be fixed in 380c390.

**Comment by dnd** [comment]
Jonathan, can you yank the gem that you released earlier, and publish a new one with this change included?

**Comment by jrochkind** [comment]
okay, thanks @dnd, sorry @masterkain, thanks @masterkain for reporting the problem. 

I will do so. 

@dnd, if you tell me your rubygems account name (which I guess is maybe just the email addr you have registered with them?), I'll add you as authorized gem releaser for cap_git_tools.

**Comment by jrochkind** [comment]
0.9.0 yanked, 0.9.1 released fixing. 

Apologies and thanks to all!
